---
# defaults file for caddy

# Packages
caddy_package: caddy
caddy_package_state: present

# Service options
caddy_service_state: started
caddy_service_enabled: true
caddy_restart_handler_state: restarted

# Debian
caddy_apt_repository_url: https://dl.cloudsmith.io/public/caddy/stable/deb/debian
caddy_apt_repository_types: [deb]
caddy_apt_repository_suites: [any-version]
caddy_apt_repository_components: [main]

caddy_apt_gpg_key: https://dl.cloudsmith.io/public/caddy/stable/gpg.key
