---
- name: Install Caddy dependencies
  ansible.builtin.apt:
    name:
      - debian-keyring
      - debian-archive-keyring
      - apt-transport-https
      - curl
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: Add Caddy repository
  ansible.builtin.deb822_repository:
    name: caddy
    uris: "{{ caddy_apt_repository_url }}"
    signed_by: "{{ caddy_apt_gpg_key }}"
    components: "{{ caddy_apt_repository_components }}"
    suites: "{{ caddy_apt_repository_suites }}"
    types: "{{ caddy_apt_repository_types }}"
    state: present
    enabled: true

- name: Update packages
  ansible.builtin.apt:
    update_cache: true
    name: "{{ caddy_package }}"
    state: "{{ caddy_package_state }}"
  notify: Restart caddy
