---
- name: Install ufw
  ansible.builtin.apt:
    name: ufw
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: Set UFW default deny policy
  community.general.ufw:
    default: deny
    direction: incoming
  notify: Enable UFW

- name: Config firewall
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop:
    - "22"
    - "80"
    - "443"
  notify: Enable UFW

- name: Install fail2ban
  ansible.builtin.apt:
    name: fail2ban
    state: present
    update_cache: true
    cache_valid_time: 3600
  notify: Enable fail2ban
